### PR TITLE
addition of French water companies owned by Nestlé

### PR DESCRIPTION
**Pull request by LLinoor**
(source : https://www.reddit.com/r/coolguides/comments/l9xl6h/a_list_of_nestle_water_brands_by_country_to_help/)

special notes : 
- Carola, Plancoët, Quézac, Saint-Lambert and Sainte-Alix were all sold by Nestle.
- i could only add the French companies due to lack of time (please excuse me)

### CODE REVIEW

**Comment by quisido** [comment]
Thanks for the contribution. I highly appreciate it. Do you happen to know the source for the image? The intention of the source attribute is more of a reputable redirection. It's not _this repository_ that is making the claim that the company is owned by Nestle, but e.g. Nestle themselves, the company itself, or a publication of some sort.

**Comment by quisido** [comment]
I was able to Vittel's claim to Nestle ownership on their website here: `https://www.vittel.com/history-vittel`, but I would not be comfortable adding the other two without sources. I haven't looked for them like I did Vittel, but maybe you would be up for it.

**Comment by LLinoor** [comment]
Sorry, it is true that the source is not official (so not reliable). I found several documents on the sites of both companies claiming to be owned by Nestle Waters. (most of them are in French, sorry). 

- Nestle : 
  Nestle's French site lists their waters companies ([here](https://www.nestle.fr/nosmarques/eaux))

- Contrex :
  In the legal notice of the site, Contrex announces that it is owned by Nestle Waters :
    `Le site www.contrex.fr est la propriété de :
     Nestlé Waters Marketing & Distribution, 12 boulevard Garibaldi 92130 Issy-les-Moulineaux [...]`

     (translation in english :
    `The site www.contrex.fr is the property of :
     Nestlé Waters Marketing & Distribution, 12 boulevard Garibaldi 92130 Issy-les-Moulineaux [...]`)

     ([here](https://www.contrex.fr/files/150811_MENTIONS_LEGALES_CONTREX))
  <hr/>

  `Nestle` and `Nestle Waters` is mentioned in the footer of the official website of Contrex ([here](https://www.contrex.fr/))

  Contrex's Wikipedia page mentions ownership by Nestlé Waters ([here](https://en.wikipedia.org/wiki/Contrex#mw-content-text:~:text=Contrex%20is%20a%20brand%20of%20mineral%20water%20owned%20since%201992%20by%20Nestl%C3%A9%20Waters))

- Hépar :
 Like Contrex, In the legal notice of the site, Hépar announces that it is owned by Nestle Waters :
    `Le site www.hepar.fr est la propriété de :
    Nestlé Waters Marketing & Distribution, adresse 34-40 rue Guynemer 92130 Issy les Moulineaux [...]`

     (translation in english :
    `The site www.hepar.fr is the property of :
    Nestlé Waters Marketing & Distribution, adress 34-40 rue Guynemer 92130 Issy les Moulineaux [...]`)

     ([here](https://www.hepar.fr/legal#block-hepar-content:~:text=Nestl%C3%A9%20Waters%20Marketing%20%26%20Distribution%2C%20adresse,RCS%20de%20Nanterre%20n%C2%B0479%20463%20044))
  <hr/>

  `Nestléwaters.fr` is mentioned in the footer of the official website of Contrex ([here](https://www.hepar.fr/))

  Hépar's Wikipedia page mentions ownership by Nestlé Waters ([here](https://fr.wikipedia.org/wiki/H%C3%A9par#mw-content-text:~:text=H%C3%A9par%20(ou%20H%C3%A9pard%20en%20ligurien)%20est%20une%20marque%20d'eau%20min%C3%A9rale%20appartenant%20%C3%A0%20Nestl%C3%A9%20Waters))

Let me know if the new sources are enough for you. I have already changed the children.ts file by adding the new sources.

**Comment by quisido** [comment]
Thank you, merged. 😁

**Pull request merged**
